PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY, name TEXT NOT NULL DEFAULT '', username TEXT NOT NULL DEFAULT '',
 bio TEXT NOT NULL DEFAULT '', title TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS users_username_idx ON users(username COLLATE NOCASE);
CREATE TABLE IF NOT EXISTS chats (
 id INTEGER PRIMARY KEY, title TEXT NOT NULL DEFAULT '', owner_id INTEGER NOT NULL DEFAULT 0,
 welcome TEXT NOT NULL DEFAULT 'Добро пожаловать, {name}!', rules TEXT NOT NULL DEFAULT '',
 log_chat_id INTEGER, warn_limit INTEGER NOT NULL DEFAULT 3,
 antispam INTEGER NOT NULL DEFAULT 1, links INTEGER NOT NULL DEFAULT 0,
 caps INTEGER NOT NULL DEFAULT 0, flood_limit INTEGER NOT NULL DEFAULT 6,
 raid_limit INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS members (
 chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL, name TEXT NOT NULL DEFAULT '',
 rank INTEGER NOT NULL DEFAULT 0, messages INTEGER NOT NULL DEFAULT 0,
 last_seen INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(chat_id,user_id)
);
CREATE INDEX IF NOT EXISTS members_chat_rank ON members(chat_id,rank);
CREATE TABLE IF NOT EXISTS stats (
 chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL, day TEXT NOT NULL,
 count INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(chat_id,user_id,day)
);
CREATE INDEX IF NOT EXISTS stats_day_idx ON stats(chat_id,day);
CREATE TABLE IF NOT EXISTS warnings (
 id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL,
 mod_id INTEGER NOT NULL, reason TEXT NOT NULL, created_at INTEGER NOT NULL,
 expires_at INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS warn_lookup ON warnings(chat_id,user_id,expires_at);
CREATE TABLE IF NOT EXISTS bans (
 chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL, mod_id INTEGER NOT NULL,
 reason TEXT NOT NULL, created_at INTEGER NOT NULL, until_at INTEGER NOT NULL DEFAULT 0,
 PRIMARY KEY(chat_id,user_id)
);
CREATE TABLE IF NOT EXISTS filters (
 chat_id INTEGER NOT NULL, phrase TEXT NOT NULL, PRIMARY KEY(chat_id,phrase)
);
CREATE TABLE IF NOT EXISTS command_access (
 chat_id INTEGER NOT NULL, command TEXT NOT NULL, min_rank INTEGER NOT NULL,
 PRIMARY KEY(chat_id,command)
);
CREATE TABLE IF NOT EXISTS custom_commands (
 chat_id INTEGER NOT NULL, trigger TEXT NOT NULL, response TEXT NOT NULL,
 PRIMARY KEY(chat_id,trigger)
);
CREATE TABLE IF NOT EXISTS notes (
 chat_id INTEGER NOT NULL, name TEXT NOT NULL, content TEXT NOT NULL,
 PRIMARY KEY(chat_id,name)
);
CREATE TABLE IF NOT EXISTS audit (
 id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, actor_id INTEGER NOT NULL,
 action TEXT NOT NULL, target_id INTEGER, detail TEXT NOT NULL DEFAULT '', at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS audit_chat ON audit(chat_id,at DESC);
CREATE TABLE IF NOT EXISTS wallet (
 user_id INTEGER PRIMARY KEY, coins INTEGER NOT NULL DEFAULT 0 CHECK(coins>=0),
 gold INTEGER NOT NULL DEFAULT 0 CHECK(gold>=0), last_daily TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS transfers (
 id INTEGER PRIMARY KEY AUTOINCREMENT, from_id INTEGER NOT NULL, to_id INTEGER NOT NULL,
 amount INTEGER NOT NULL, at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS reputation (
 target_id INTEGER PRIMARY KEY, score INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS rep_votes (
 from_id INTEGER NOT NULL, to_id INTEGER NOT NULL, day TEXT NOT NULL,
 PRIMARY KEY(from_id,to_id,day)
);
CREATE TABLE IF NOT EXISTS marriages (
 user1 INTEGER NOT NULL UNIQUE, user2 INTEGER NOT NULL UNIQUE, at INTEGER NOT NULL,
 PRIMARY KEY(user1,user2)
);
CREATE TABLE IF NOT EXISTS proposals (
 from_id INTEGER NOT NULL, to_id INTEGER NOT NULL, created_at INTEGER NOT NULL,
 PRIMARY KEY(from_id,to_id)
);
CREATE TABLE IF NOT EXISTS duels (
 id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, challenger INTEGER NOT NULL,
 opponent INTEGER NOT NULL, stake INTEGER NOT NULL, created_at INTEGER NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending'
);
CREATE TABLE IF NOT EXISTS clans (
 id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, name TEXT NOT NULL,
 owner_id INTEGER NOT NULL, created_at INTEGER NOT NULL, UNIQUE(chat_id,name)
);
CREATE TABLE IF NOT EXISTS clan_members (
 clan_id INTEGER NOT NULL, user_id INTEGER NOT NULL, joined_at INTEGER NOT NULL,
 PRIMARY KEY(clan_id,user_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS clan_unique_user ON clan_members(user_id);
CREATE TABLE IF NOT EXISTS bookmarks (
 user_id INTEGER NOT NULL, chat_id INTEGER NOT NULL, message_id INTEGER NOT NULL,
 name TEXT NOT NULL, PRIMARY KEY(user_id,name)
);
CREATE TABLE IF NOT EXISTS reminders (
 id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, user_id INTEGER NOT NULL,
 text TEXT NOT NULL, due_at INTEGER NOT NULL, sent INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS reminders_due ON reminders(sent,due_at);
CREATE TABLE IF NOT EXISTS giveaways (
 id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, creator INTEGER NOT NULL,
 prize TEXT NOT NULL, deadline INTEGER NOT NULL, winner_id INTEGER, finished INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS giveaway_entries (
 giveaway_id INTEGER NOT NULL, user_id INTEGER NOT NULL, PRIMARY KEY(giveaway_id,user_id)
);
CREATE TABLE IF NOT EXISTS awards (
 id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, target_id INTEGER NOT NULL,
 giver_id INTEGER NOT NULL, name TEXT NOT NULL, created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS awards_target ON awards(chat_id,target_id);
CREATE TABLE IF NOT EXISTS federations (
 id INTEGER PRIMARY KEY AUTOINCREMENT, owner_id INTEGER NOT NULL, name TEXT NOT NULL, created_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS federation_chats (
 chat_id INTEGER PRIMARY KEY, federation_id INTEGER NOT NULL REFERENCES federations(id)
);
CREATE TABLE IF NOT EXISTS federation_codes (
 code_hash TEXT PRIMARY KEY, federation_id INTEGER NOT NULL REFERENCES federations(id), expires_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS chat_timers (
 id INTEGER PRIMARY KEY AUTOINCREMENT, chat_id INTEGER NOT NULL, owner_id INTEGER NOT NULL,
 content TEXT NOT NULL, every_seconds INTEGER NOT NULL, next_at INTEGER NOT NULL,
 active INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS chat_timers_due ON chat_timers(active,next_at);
